// <auto-generated />
namespace ActsModel.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class ActTypeAdded3 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ActTypeAdded3));
        
        string IMigrationMetadata.Id
        {
            get { return "201803161742533_ActTypeAdded3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
