namespace ActsModel.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class modelProps : DbMigration
    {
        public override void Up()
        {
            CreateTable(
                "dbo.Photos",
                c => new
                    {
                        Id = c.String(nullable: false, maxLength: 128),
                        Description = c.String(),
                        PhotoTable_Id = c.Int(),
                    })
                .PrimaryKey(t => t.Id)
                .ForeignKey("dbo.ActBases", t => t.PhotoTable_Id)
                .Index(t => t.PhotoTable_Id);
            
            AddColumn("dbo.ActBases", "ActNum", c => c.String());
            AddColumn("dbo.ActBases", "DateTimeCreation", c => c.DateTime());
            AddColumn("dbo.ActBases", "PlaceActCreation", c => c.String());
            AddColumn("dbo.ActBases", "ActCreator", c => c.String());
            AddColumn("dbo.ActBases", "BaseOnOrder", c => c.String());
            AddColumn("dbo.ActBases", "BaseOnOrderDate", c => c.DateTime());
            AddColumn("dbo.ActBases", "OrderNum", c => c.String());
            AddColumn("dbo.ActBases", "AttendingPersonsInfo", c => c.String());
            AddColumn("dbo.ActBases", "CheckType", c => c.String());
            AddColumn("dbo.ActBases", "AreaAddress", c => c.String());
            AddColumn("dbo.ActBases", "AreaSquare", c => c.String());
            AddColumn("dbo.ActBases", "UserInfo", c => c.String());
            AddColumn("dbo.ActBases", "CheckDateStart", c => c.DateTime());
            AddColumn("dbo.ActBases", "CheckDateFinish", c => c.DateTime());
            AddColumn("dbo.ActBases", "CheckResults", c => c.String());
            AddColumn("dbo.ActBases", "InspectedPersonInfo", c => c.String());
            AddColumn("dbo.ActBases", "ApplicationContent", c => c.String());
            AddColumn("dbo.ActBases", "DuringCheckActivity", c => c.String());
            AddColumn("dbo.ActBases", "AdditionsToAct", c => c.String());
            AddColumn("dbo.ActBases", "TerritorialBodyName", c => c.String());
            AddColumn("dbo.ActBases", "PlaceActCreation1", c => c.String());
            AddColumn("dbo.ActBases", "DateTimeCreation1", c => c.DateTime());
            AddColumn("dbo.ActBases", "ActNum1", c => c.String());
            AddColumn("dbo.ActBases", "CheckingPlace", c => c.String());
            AddColumn("dbo.ActBases", "OnBaseOfDocs", c => c.String());
            AddColumn("dbo.ActBases", "CheckType1", c => c.String());
            AddColumn("dbo.ActBases", "ChekingTarget", c => c.String());
            AddColumn("dbo.ActBases", "DateAndTimeOfCheck", c => c.String());
            AddColumn("dbo.ActBases", "CommonCheckDuration", c => c.String());
            AddColumn("dbo.ActBases", "ActCreatedBy", c => c.String());
            AddColumn("dbo.ActBases", "FamiliarPersonInfo", c => c.String());
            AddColumn("dbo.ActBases", "ProsecutorDecision", c => c.String());
            AddColumn("dbo.ActBases", "CheckersInfo", c => c.String());
            AddColumn("dbo.ActBases", "BeholdersInfo", c => c.String());
            AddColumn("dbo.ActBases", "RequirementsViolations", c => c.String());
            AddColumn("dbo.ActBases", "DiscrepanciesInfo", c => c.String());
            AddColumn("dbo.ActBases", "NonComplianceFacts", c => c.String());
            AddColumn("dbo.ActBases", "NoViolations", c => c.String());
            AddColumn("dbo.ActBases", "DocsForAct", c => c.String());
            AddColumn("dbo.ActBases", "PersonInfo", c => c.String());
            AddColumn("dbo.ActBases", "TerritorialBodyName1", c => c.String());
            AddColumn("dbo.ActBases", "ActNum2", c => c.String());
            AddColumn("dbo.ActBases", "DateCreation", c => c.DateTime());
            AddColumn("dbo.ActBases", "PlaceAndTimeCreation", c => c.String());
            AddColumn("dbo.ActBases", "ReasonRequisites", c => c.String());
            AddColumn("dbo.ActBases", "CheckContactInfos", c => c.String());
            AddColumn("dbo.ActBases", "InvolvedContactInfos", c => c.String());
            AddColumn("dbo.ActBases", "CadastralNum", c => c.String());
            AddColumn("dbo.ActBases", "AreaAddress1", c => c.String());
            AddColumn("dbo.ActBases", "AreaSquare1", c => c.String());
            AddColumn("dbo.ActBases", "ProvidedToInfo", c => c.String());
            AddColumn("dbo.ActBases", "DeviceParameters", c => c.String());
            AddColumn("dbo.ActBases", "ResearchResults", c => c.String());
            AddColumn("dbo.ActBases", "ActAnnexes", c => c.String());
            AddColumn("dbo.ActBases", "TerritorialBodyName2", c => c.String());
            AddColumn("dbo.ActBases", "Date", c => c.DateTime());
            AddColumn("dbo.ActBases", "ActNum3", c => c.String());
            AddColumn("dbo.ActBases", "MeasureAuthorInfo", c => c.String());
            AddColumn("dbo.ActBases", "RepresentativePersonInfo", c => c.String());
            AddColumn("dbo.ActBases", "AreaAddress2", c => c.String());
            AddColumn("dbo.ActBases", "DeviceInfo", c => c.String());
            AddColumn("dbo.ActBases", "AreaSquare2", c => c.String());
            AddColumn("dbo.ActBases", "AreaCalculation", c => c.String());
            AddColumn("dbo.ActBases", "SpecialMarks", c => c.String());
            AddColumn("dbo.ActBases", "MunitipalControlName", c => c.String());
            AddColumn("dbo.ActBases", "AdditionToActDate", c => c.DateTime());
            AddColumn("dbo.ActBases", "ActNum4", c => c.String());
            AddColumn("dbo.ActBases", "PersonsInfo", c => c.String());
            AddColumn("dbo.ActBases", "AreaInfo", c => c.String());
            AddColumn("dbo.ActBases", "DeviceInfo1", c => c.String());
            AddColumn("dbo.ActBases", "PhototableCreator", c => c.String());
            AddColumn("dbo.ActBases", "InspectationTargetInfo", c => c.String());
            AddColumn("dbo.ActBases", "TargetAddress", c => c.String());
            AddColumn("dbo.ActBases", "CheckBase", c => c.String());
            AddColumn("dbo.ActBases", "CheckDateStart1", c => c.DateTime());
            AddColumn("dbo.ActBases", "CheckTimeStart", c => c.DateTime());
            AddColumn("dbo.ActBases", "Additions", c => c.String());
            AddColumn("dbo.ActBases", "DateTimeOfDocCreation", c => c.DateTime());
            AddColumn("dbo.ActBases", "JournalStartDate", c => c.String());
            AddColumn("dbo.ActBases", "PersonInfo1", c => c.String());
            AddColumn("dbo.ActBases", "Address", c => c.String());
            AddColumn("dbo.ActBases", "DifferentInfo", c => c.String());
            AddColumn("dbo.ActBases", "ResponsiblePersonInfo", c => c.String());
            AddColumn("dbo.ActBases", "ResponsiblePersonBossInfo", c => c.String());
            AddColumn("dbo.ActBases", "CheckDateStartAndFinish", c => c.String());
            AddColumn("dbo.ActBases", "CommonCheckDuration1", c => c.String());
            AddColumn("dbo.ActBases", "StateControlName", c => c.String());
            AddColumn("dbo.ActBases", "DateNumOrOrderOfCheck", c => c.String());
            AddColumn("dbo.ActBases", "CheckAimTaskAndObject", c => c.String());
            AddColumn("dbo.ActBases", "CheckType2", c => c.String());
            AddColumn("dbo.ActBases", "DateNumOfCheckRes", c => c.String());
            AddColumn("dbo.ActBases", "FoundViolations", c => c.String());
            AddColumn("dbo.ActBases", "DateNumOfContentOfElimination", c => c.String());
            AddColumn("dbo.ActBases", "CheckerPersonInfo", c => c.String());
            AddColumn("dbo.ActBases", "TerritorialBodyName3", c => c.String());
            AddColumn("dbo.ActBases", "ApprovedByInfo", c => c.String());
            AddColumn("dbo.ActBases", "ApprovedTime", c => c.DateTime());
            AddColumn("dbo.ActBases", "ScheduledInspectionYear", c => c.String());
            AddColumn("dbo.ActBases", "EarthObject", c => c.String());
            AddColumn("dbo.ActBases", "CitizenName", c => c.String());
            AddColumn("dbo.ActBases", "CheckAim", c => c.String());
            AddColumn("dbo.ActBases", "CheckBase1", c => c.String());
            AddColumn("dbo.ActBases", "CheckStartDate", c => c.String());
            AddColumn("dbo.ActBases", "CheckDurationInDays", c => c.String());
            AddColumn("dbo.ActBases", "FederalBodyName", c => c.String());
            AddColumn("dbo.ActBases", "TerritorialBodyName4", c => c.String());
            AddColumn("dbo.ActBases", "CheckType3", c => c.String());
            AddColumn("dbo.ActBases", "OrderNum1", c => c.String());
            AddColumn("dbo.ActBases", "InspectionTarget", c => c.String());
            AddColumn("dbo.ActBases", "TargetPlace", c => c.String());
            AddColumn("dbo.ActBases", "CheckerInfo", c => c.String());
            AddColumn("dbo.ActBases", "ExpertsInfo", c => c.String());
            AddColumn("dbo.ActBases", "CheckingScopes", c => c.String());
            AddColumn("dbo.ActBases", "CheckingAim", c => c.String());
            AddColumn("dbo.ActBases", "CheckingTasks", c => c.String());
            AddColumn("dbo.ActBases", "CheckingDuration", c => c.String());
            AddColumn("dbo.ActBases", "CheckingTimeStart", c => c.DateTime());
            AddColumn("dbo.ActBases", "CheckingTimeFinish", c => c.DateTime());
            AddColumn("dbo.ActBases", "RightCheckingBases", c => c.String());
            AddColumn("dbo.ActBases", "MandatoryRequirements", c => c.String());
            AddColumn("dbo.ActBases", "CheckingEvents", c => c.String());
            AddColumn("dbo.ActBases", "ProvisionsListOfStateControl", c => c.String());
            AddColumn("dbo.ActBases", "DocumentsForSuccess", c => c.String());
            AddColumn("dbo.ActBases", "OrderCreatorInfo", c => c.String());
            AddColumn("dbo.ActBases", "Date1", c => c.DateTime());
            AddColumn("dbo.ActBases", "Num", c => c.String());
            AddColumn("dbo.ActBases", "CreationPlace", c => c.String());
            AddColumn("dbo.ActBases", "ActCreatorInfo", c => c.String());
            AddColumn("dbo.ActBases", "InPresenceOfPersonInfo", c => c.String());
            AddColumn("dbo.ActBases", "ViolationDescription", c => c.String());
            AddColumn("dbo.ActBases", "ViolationAuthorInfo", c => c.String());
            AddColumn("dbo.ActBases", "CodexSection", c => c.String());
            AddColumn("dbo.ActBases", "CodexArticle", c => c.String());
            AddColumn("dbo.ActBases", "PersonExplanation", c => c.String());
            AddColumn("dbo.ActBases", "SpecialMarks1", c => c.String());
            AddColumn("dbo.ActBases", "ProtocolCreatorInfo", c => c.String());
            AddColumn("dbo.ActBases", "Date2", c => c.DateTime());
            AddColumn("dbo.ActBases", "Num1", c => c.String());
            AddColumn("dbo.ActBases", "CreatorInfo", c => c.String());
            AddColumn("dbo.ActBases", "AreaAddress3", c => c.String());
            AddColumn("dbo.ActBases", "AreaSquare3", c => c.String());
            AddColumn("dbo.ActBases", "AreaUserInfo", c => c.String());
            AddColumn("dbo.ActBases", "ViolationDescription1", c => c.String());
            AddColumn("dbo.ActBases", "ViolationAuthorInfo1", c => c.String());
            AddColumn("dbo.ActBases", "CorrectToDate", c => c.DateTime());
            AddColumn("dbo.ActBases", "MunicipalAuthorityForDocuments", c => c.String());
            AddColumn("dbo.ActBases", "MunicipalAuthorityAddress", c => c.String());
            AddColumn("dbo.ActBases", "PrescriptionDeliveryMark", c => c.String());
        }
        
        public override void Down()
        {
            DropForeignKey("dbo.Photos", "PhotoTable_Id", "dbo.ActBases");
            DropIndex("dbo.Photos", new[] { "PhotoTable_Id" });
            AlterColumn("dbo.ActBases", "Discriminator", c => c.String(nullable: false, maxLength: 128));
            DropColumn("dbo.ActBases", "PrescriptionDeliveryMark");
            DropColumn("dbo.ActBases", "MunicipalAuthorityAddress");
            DropColumn("dbo.ActBases", "MunicipalAuthorityForDocuments");
            DropColumn("dbo.ActBases", "CorrectToDate");
            DropColumn("dbo.ActBases", "ViolationAuthorInfo1");
            DropColumn("dbo.ActBases", "ViolationDescription1");
            DropColumn("dbo.ActBases", "AreaUserInfo");
            DropColumn("dbo.ActBases", "AreaSquare3");
            DropColumn("dbo.ActBases", "AreaAddress3");
            DropColumn("dbo.ActBases", "CreatorInfo");
            DropColumn("dbo.ActBases", "Num1");
            DropColumn("dbo.ActBases", "Date2");
            DropColumn("dbo.ActBases", "ProtocolCreatorInfo");
            DropColumn("dbo.ActBases", "SpecialMarks1");
            DropColumn("dbo.ActBases", "PersonExplanation");
            DropColumn("dbo.ActBases", "CodexArticle");
            DropColumn("dbo.ActBases", "CodexSection");
            DropColumn("dbo.ActBases", "ViolationAuthorInfo");
            DropColumn("dbo.ActBases", "ViolationDescription");
            DropColumn("dbo.ActBases", "InPresenceOfPersonInfo");
            DropColumn("dbo.ActBases", "ActCreatorInfo");
            DropColumn("dbo.ActBases", "CreationPlace");
            DropColumn("dbo.ActBases", "Num");
            DropColumn("dbo.ActBases", "Date1");
            DropColumn("dbo.ActBases", "OrderCreatorInfo");
            DropColumn("dbo.ActBases", "DocumentsForSuccess");
            DropColumn("dbo.ActBases", "ProvisionsListOfStateControl");
            DropColumn("dbo.ActBases", "CheckingEvents");
            DropColumn("dbo.ActBases", "MandatoryRequirements");
            DropColumn("dbo.ActBases", "RightCheckingBases");
            DropColumn("dbo.ActBases", "CheckingTimeFinish");
            DropColumn("dbo.ActBases", "CheckingTimeStart");
            DropColumn("dbo.ActBases", "CheckingDuration");
            DropColumn("dbo.ActBases", "CheckingTasks");
            DropColumn("dbo.ActBases", "CheckingAim");
            DropColumn("dbo.ActBases", "CheckingScopes");
            DropColumn("dbo.ActBases", "ExpertsInfo");
            DropColumn("dbo.ActBases", "CheckerInfo");
            DropColumn("dbo.ActBases", "TargetPlace");
            DropColumn("dbo.ActBases", "InspectionTarget");
            DropColumn("dbo.ActBases", "OrderNum1");
            DropColumn("dbo.ActBases", "CheckType3");
            DropColumn("dbo.ActBases", "TerritorialBodyName4");
            DropColumn("dbo.ActBases", "FederalBodyName");
            DropColumn("dbo.ActBases", "CheckDurationInDays");
            DropColumn("dbo.ActBases", "CheckStartDate");
            DropColumn("dbo.ActBases", "CheckBase1");
            DropColumn("dbo.ActBases", "CheckAim");
            DropColumn("dbo.ActBases", "CitizenName");
            DropColumn("dbo.ActBases", "EarthObject");
            DropColumn("dbo.ActBases", "ScheduledInspectionYear");
            DropColumn("dbo.ActBases", "ApprovedTime");
            DropColumn("dbo.ActBases", "ApprovedByInfo");
            DropColumn("dbo.ActBases", "TerritorialBodyName3");
            DropColumn("dbo.ActBases", "CheckerPersonInfo");
            DropColumn("dbo.ActBases", "DateNumOfContentOfElimination");
            DropColumn("dbo.ActBases", "FoundViolations");
            DropColumn("dbo.ActBases", "DateNumOfCheckRes");
            DropColumn("dbo.ActBases", "CheckType2");
            DropColumn("dbo.ActBases", "CheckAimTaskAndObject");
            DropColumn("dbo.ActBases", "DateNumOrOrderOfCheck");
            DropColumn("dbo.ActBases", "StateControlName");
            DropColumn("dbo.ActBases", "CommonCheckDuration1");
            DropColumn("dbo.ActBases", "CheckDateStartAndFinish");
            DropColumn("dbo.ActBases", "ResponsiblePersonBossInfo");
            DropColumn("dbo.ActBases", "ResponsiblePersonInfo");
            DropColumn("dbo.ActBases", "DifferentInfo");
            DropColumn("dbo.ActBases", "Address");
            DropColumn("dbo.ActBases", "PersonInfo1");
            DropColumn("dbo.ActBases", "JournalStartDate");
            DropColumn("dbo.ActBases", "DateTimeOfDocCreation");
            DropColumn("dbo.ActBases", "Additions");
            DropColumn("dbo.ActBases", "CheckTimeStart");
            DropColumn("dbo.ActBases", "CheckDateStart1");
            DropColumn("dbo.ActBases", "CheckBase");
            DropColumn("dbo.ActBases", "TargetAddress");
            DropColumn("dbo.ActBases", "InspectationTargetInfo");
            DropColumn("dbo.ActBases", "PhototableCreator");
            DropColumn("dbo.ActBases", "DeviceInfo1");
            DropColumn("dbo.ActBases", "AreaInfo");
            DropColumn("dbo.ActBases", "PersonsInfo");
            DropColumn("dbo.ActBases", "ActNum4");
            DropColumn("dbo.ActBases", "AdditionToActDate");
            DropColumn("dbo.ActBases", "MunitipalControlName");
            DropColumn("dbo.ActBases", "SpecialMarks");
            DropColumn("dbo.ActBases", "AreaCalculation");
            DropColumn("dbo.ActBases", "AreaSquare2");
            DropColumn("dbo.ActBases", "DeviceInfo");
            DropColumn("dbo.ActBases", "AreaAddress2");
            DropColumn("dbo.ActBases", "RepresentativePersonInfo");
            DropColumn("dbo.ActBases", "MeasureAuthorInfo");
            DropColumn("dbo.ActBases", "ActNum3");
            DropColumn("dbo.ActBases", "Date");
            DropColumn("dbo.ActBases", "TerritorialBodyName2");
            DropColumn("dbo.ActBases", "ActAnnexes");
            DropColumn("dbo.ActBases", "ResearchResults");
            DropColumn("dbo.ActBases", "DeviceParameters");
            DropColumn("dbo.ActBases", "ProvidedToInfo");
            DropColumn("dbo.ActBases", "AreaSquare1");
            DropColumn("dbo.ActBases", "AreaAddress1");
            DropColumn("dbo.ActBases", "CadastralNum");
            DropColumn("dbo.ActBases", "InvolvedContactInfos");
            DropColumn("dbo.ActBases", "CheckContactInfos");
            DropColumn("dbo.ActBases", "ReasonRequisites");
            DropColumn("dbo.ActBases", "PlaceAndTimeCreation");
            DropColumn("dbo.ActBases", "DateCreation");
            DropColumn("dbo.ActBases", "ActNum2");
            DropColumn("dbo.ActBases", "TerritorialBodyName1");
            DropColumn("dbo.ActBases", "PersonInfo");
            DropColumn("dbo.ActBases", "DocsForAct");
            DropColumn("dbo.ActBases", "NoViolations");
            DropColumn("dbo.ActBases", "NonComplianceFacts");
            DropColumn("dbo.ActBases", "DiscrepanciesInfo");
            DropColumn("dbo.ActBases", "RequirementsViolations");
            DropColumn("dbo.ActBases", "BeholdersInfo");
            DropColumn("dbo.ActBases", "CheckersInfo");
            DropColumn("dbo.ActBases", "ProsecutorDecision");
            DropColumn("dbo.ActBases", "FamiliarPersonInfo");
            DropColumn("dbo.ActBases", "ActCreatedBy");
            DropColumn("dbo.ActBases", "CommonCheckDuration");
            DropColumn("dbo.ActBases", "DateAndTimeOfCheck");
            DropColumn("dbo.ActBases", "ChekingTarget");
            DropColumn("dbo.ActBases", "CheckType1");
            DropColumn("dbo.ActBases", "OnBaseOfDocs");
            DropColumn("dbo.ActBases", "CheckingPlace");
            DropColumn("dbo.ActBases", "ActNum1");
            DropColumn("dbo.ActBases", "DateTimeCreation1");
            DropColumn("dbo.ActBases", "PlaceActCreation1");
            DropColumn("dbo.ActBases", "TerritorialBodyName");
            DropColumn("dbo.ActBases", "AdditionsToAct");
            DropColumn("dbo.ActBases", "DuringCheckActivity");
            DropColumn("dbo.ActBases", "ApplicationContent");
            DropColumn("dbo.ActBases", "InspectedPersonInfo");
            DropColumn("dbo.ActBases", "CheckResults");
            DropColumn("dbo.ActBases", "CheckDateFinish");
            DropColumn("dbo.ActBases", "CheckDateStart");
            DropColumn("dbo.ActBases", "UserInfo");
            DropColumn("dbo.ActBases", "AreaSquare");
            DropColumn("dbo.ActBases", "AreaAddress");
            DropColumn("dbo.ActBases", "CheckType");
            DropColumn("dbo.ActBases", "AttendingPersonsInfo");
            DropColumn("dbo.ActBases", "OrderNum");
            DropColumn("dbo.ActBases", "BaseOnOrderDate");
            DropColumn("dbo.ActBases", "BaseOnOrder");
            DropColumn("dbo.ActBases", "ActCreator");
            DropColumn("dbo.ActBases", "PlaceActCreation");
            DropColumn("dbo.ActBases", "DateTimeCreation");
            DropColumn("dbo.ActBases", "ActNum");
            DropTable("dbo.Photos");
        }
    }
}
